Full Loguru Logger
nonebotjs/koishi-plugin-nonebot pull request #13
Opened 2023-06-08 15:11 UTC by Chinese-Cyq20100313

2023-06-10 06:20 UTC, shigma requested changes
请不要修改任何已经可以运行的代码。

2023-06-10 06:22 UTC, shigma requested changes
请不要引入 Loguru，而是应该在仓库中实现它。

2023-06-10 12:26 UTC, shigma commented on packages/nonebot/src/internal/index.ts
> +  constructor(protected ctx: Context) {ctx.bots}
草，这啥（

2023-06-10 12:27 UTC, shigma commented on scripts/nbp.ts
> +import {extract} from 'tar'
这都没修啊，请改回正确的格式

2023-06-10 14:58 UTC, Chinese-Cyq20100313 commented on packages/nonebot/src/internal/index.ts
> +  constructor(protected ctx: Context) {ctx.bots}
看TypeHint忘删了，明天改下

2023-06-10 14:59 UTC, Chinese-Cyq20100313 commented on scripts/nbp.ts
> +import {extract} from 'tar'
是大括号没加空格？明天调下我IDE配置

2023-06-10 15:00 UTC, Chinese-Cyq20100313 commented on packages/nonebot/src/internal/index.ts
> +  constructor(protected ctx: Context) {ctx.bots}
在网页端也不是不能改

2023-06-12 12:10 UTC, Chinese-Cyq20100313 commented on scripts/nbp.ts
> +import {extract} from 'tar'
可以了

2023-06-13 06:07 UTC, shigma requested changes

2023-06-13 06:07 UTC, shigma commented on scripts/nbp.ts
> +  await mkdir(pathCache, {recursive: true})
……

2023-06-13 13:41 UTC, Chinese-Cyq20100313 commented on scripts/nbp.ts
> +  await mkdir(pathCache, {recursive: true})
az

2023-06-15 10:32 UTC, Chinese-Cyq20100313 commented
忘了 nbp 没让它下 loguru 包，我去修一下

2023-06-15 15:59 UTC, shigma requested changes

2023-06-15 15:59 UTC, shigma commented on packages/nonebot/python/nonebot/__init__.py
> +logger.success("nonebot loaded")
不魔改 js 了换成魔改 py 了是吧？有完没完？是不是故意来浪费我时间的？

2023-06-15 16:00 UTC, shigma commented
一个 pr 到处瞎改，核心改动明明就几行拖一周改几百行。关了。

2023-06-15 16:00 UTC, closed without merging

2023-06-16 09:35 UTC, Chinese-Cyq20100313 commented
> 一个 pr 到处瞎改，核心改动明明就几行拖一周改几百行。关了。

下次不按 Alt+Shift+L 了（悲）

2023-06-16 10:48 UTC, shigma commented
> > 一个 pr 到处瞎改，核心改动明明就几行拖一周改几百行。关了。
> 
> 下次不按 Alt+Shift+L 了（悲）

你不方便改的话我可以等有空的时候自己写，然后 co-author 你。我认可你的贡献但是反正 pr 是不能合。

2023-06-18 01:18 UTC, Chinese-Cyq20100313 commented
现在天天被抓去期末复习
________________________________
From: Shigma ***@***.***>
Sent: Friday, June 16, 2023 6:48:43 PM
To: nonebotjs/koishi-plugin-nonebot ***@***.***>
Cc: Cyan ***@***.***>; Author ***@***.***>
Subject: Re: [nonebotjs/koishi-plugin-nonebot] Use Nonebot2's default loguru logger to forward to reggol instead of directly replacing it with reggol logger (PR #13)


一个 pr 到处瞎改，核心改动明明就几行拖一周改几百行。关了。

下次不按 Alt+Shift+L 了（悲）

你不方便改的话我可以等有空的时候自己写，然后 co-author 你。我认可你的贡献但是反正 pr 是不能合。

―
Reply to this email directly, view it on GitHub<https://github.com/nonebotjs/koishi-plugin-nonebot/pull/13#issuecomment-1594486494>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQLAIBBZOP5FHAXQX3RFIELXLQ2YXANCNFSM6AAAAAAY7OBVMM>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-07-09 00:43 UTC, CyanChanges commented
过有点久，那我重新pr写吧